/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import java.util.List;

import control.GerInterGrafica;
import java.awt.Component;
import java.text.ParseException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.ItemVenda;
import model.Produto;
import model.Venda;

/**
 *
 * @author Gabriel
 */
public class DlgVenda extends javax.swing.JDialog {

    private GerInterGrafica gerIG;
    private Cliente clienteSelecionado;
    private Produto produtoSelecionado;
    private Venda vendaSelecionada;
    private List<ItemVenda> itendsDaListaProduto;
    private String valornaTela = "";
    private Double contadorValor = 0.0;

    /**
     * Creates new form DlgVenda
     */
    public DlgVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        clienteSelecionado = null;
        produtoSelecionado = null;
        itendsDaListaProduto = null;
        vendaSelecionada = null;
        habilitarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        HistVendas = new javax.swing.JMenu();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFildCodCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonCadCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonPesqProduto = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        SpinnerQtdProduto = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtValorUn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        buttonAddProd = new javax.swing.JButton();
        buttonRemoProd = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotalEscrito = new javax.swing.JLabel();
        buttonPesqCliente = new javax.swing.JButton();
        dataVenda = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDinheiro = new javax.swing.JRadioButton();
        lblPix = new javax.swing.JRadioButton();
        lblPicpay = new javax.swing.JRadioButton();
        lblDebito = new javax.swing.JRadioButton();
        lblCredito = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        FinalizarVenda = new javax.swing.JButton();
        CancelarVenda = new javax.swing.JButton();
        btnHistVenda = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        HistVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-relatório-40.png"))); // NOI18N
        HistVendas.setText("Historico de vendas");
        HistVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistVendasMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(54, 51, 131));

        jPanel5.setBackground(new java.awt.Color(255, 57, 56));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/Logo Branca.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addContainerGap(733, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda"));

        jLabel1.setText("Cód.Cliente");

        txtFildCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFildCodClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel6.setText("Celular");

        jLabel7.setText("Data");

        jLabel8.setText("CPF");

        buttonCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-adicionar-grupo-de-usuários-mulher-homem-30.png"))); // NOI18N
        buttonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadClienteActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-vendas-100.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel9.setText("Cód.Produto");

        jLabel11.setText("Nome do Produto");

        buttonPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-pesquisar-25.png"))); // NOI18N
        buttonPesqProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPesqProdutoMouseClicked(evt);
            }
        });
        buttonPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesqProdutoActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantidade");

        jLabel13.setText("Valor Un");

        jLabel14.setText("Valor Total");

        buttonAddProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-adicionar-40.png"))); // NOI18N
        buttonAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProdActionPerformed(evt);
            }
        });

        buttonRemoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-menos-40.png"))); // NOI18N
        buttonRemoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoProdActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Total:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("R$:");

        lblTotalEscrito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalEscrito.setText("Valor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAddProd)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodProduto)
                        .addComponent(SpinnerQtdProduto))
                    .addComponent(buttonRemoProd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonPesqProduto)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProduto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalEscrito))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonPesqProduto)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRemoProd)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(SpinnerQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lblTotalEscrito)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonAddProd)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-pesquisar-25.png"))); // NOI18N
        buttonPesqCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPesqClienteMouseClicked(evt);
            }
        });
        buttonPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesqClienteActionPerformed(evt);
            }
        });

        try {
            dataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFildCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesqCliente)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(154, 154, 154)
                            .addComponent(buttonCadCliente))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCpf))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtFildCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonPesqCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(buttonCadCliente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Venda");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de pagamento"));

        buttonGroup1.add(lblDinheiro);
        lblDinheiro.setMnemonic('D');
        lblDinheiro.setText("Dinheiro");

        buttonGroup1.add(lblPix);
        lblPix.setMnemonic('P');
        lblPix.setText("Pix");

        buttonGroup1.add(lblPicpay);
        lblPicpay.setMnemonic('Y');
        lblPicpay.setText("Picpay");

        buttonGroup1.add(lblDebito);
        lblDebito.setMnemonic('T');
        lblDebito.setText("Cartão Débito");

        buttonGroup1.add(lblCredito);
        lblCredito.setMnemonic('W');
        lblCredito.setText("Cartão Crédito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblDinheiro)
                .addGap(100, 100, 100)
                .addComponent(lblPix)
                .addGap(100, 100, 100)
                .addComponent(lblPicpay)
                .addGap(101, 101, 101)
                .addComponent(lblDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(lblCredito)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDinheiro)
                    .addComponent(lblPix)
                    .addComponent(lblPicpay)
                    .addComponent(lblDebito)
                    .addComponent(lblCredito))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório de Venda"));

        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Valor Unitario", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(tabelaVenda);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-ok-40.png"))); // NOI18N
        FinalizarVenda.setText("Finalizar Venda");
        FinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarVendaActionPerformed(evt);
            }
        });

        CancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-cancelar-40.png"))); // NOI18N
        CancelarVenda.setText("Cancelar");
        CancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarVendaActionPerformed(evt);
            }
        });

        btnHistVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-relatório-40.png"))); // NOI18N
        btnHistVenda.setText("Historico de Venda");
        btnHistVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistVendaActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icons8-editar-40.png"))); // NOI18N
        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(FinalizarVenda)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarVenda)
                        .addGap(186, 186, 186)
                        .addComponent(btnHistVenda))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalizarVenda)
                    .addComponent(CancelarVenda)
                    .addComponent(btnHistVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesqClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPesqClienteMouseClicked
        GerInterGrafica.getInstance().abrirJanelaPesqCliente();
    }//GEN-LAST:event_buttonPesqClienteMouseClicked

    private void buttonPesqProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPesqProdutoMouseClicked
        GerInterGrafica.getInstance().abrirJanelaPesqProduto();
    }//GEN-LAST:event_buttonPesqProdutoMouseClicked

    private void buttonPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesqClienteActionPerformed
        clienteSelecionado = gerIG.getInstance().abrirJanelaPesqCliente();
        try {
            this.preencherCamposCliente(clienteSelecionado);
        } catch (ParseException ex) {
            Logger.getLogger(DlgVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonPesqClienteActionPerformed

    private void buttonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadClienteActionPerformed
        gerIG.getInstance().abrirJanCadCliente();
    }//GEN-LAST:event_buttonCadClienteActionPerformed

    private void buttonPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesqProdutoActionPerformed
        produtoSelecionado = gerIG.getInstance().abrirJanelaPesqProduto();
        try {
            this.preencherCamposProduto(produtoSelecionado);
        } catch (ParseException ex) {
            Logger.getLogger(DlgVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPesqProdutoActionPerformed

    private void buttonAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProdActionPerformed
        if (produtoSelecionado != null) {
            Produto produtoAddTabela = this.produtoSelecionado;
            int qtde = (int) SpinnerQtdProduto.getValue();
            String valorunitario = txtValorUn.getText();
            String valortotal = txtValorTotal.getText();

            if (Integer.parseInt(valortotal) < Integer.parseInt(valorunitario)) {
                JOptionPane.showMessageDialog(this, "Valor total não pode ser menor que o valor unitário");
            } else {
                if (qtde < 1) {
                    JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero");
                } else {
                    // Verifica se o produto já está na tabela
                    boolean produtoJaCadastrado = false;
                    DefaultTableModel model = (DefaultTableModel) tabelaVenda.getModel();
                    for (int i = 0; i < model.getRowCount(); i++) {
                        Produto produtoNaTabela = (Produto) model.getValueAt(i, 0); // Supondo que a coluna 0 tenha o produto
                        if (produtoNaTabela.equals(produtoAddTabela)) {
                            produtoJaCadastrado = true;
                            break;
                        }
                    }

                    if (produtoJaCadastrado) {
                        JOptionPane.showMessageDialog(this, "Este produto já está cadastrado na tabela.", "Erro", JOptionPane.ERROR_MESSAGE);
                    } else {
                        try {
                            double valor = Double.parseDouble(valortotal);
                            adicionarTabela(produtoAddTabela, qtde, valor);
                            contadorValor = (contadorValor + valor) * qtde;
                            valornaTela = String.valueOf(contadorValor);
                            lblTotalEscrito.setText(valornaTela);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "O valor total não é válido.", "Erro", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto antes de adicionar à tabela.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonAddProdActionPerformed

    private void buttonRemoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoProdActionPerformed

        int linha = tabelaVenda.getSelectedRow();

        if (linha >= 0) {
            double colunaValorTotal = (double) tabelaVenda.getModel().getValueAt(linha, 3);
            tabelaVenda.removeRowSelectionInterval(linha, linha);
            contadorValor = contadorValor - colunaValorTotal;
            valornaTela = String.valueOf(contadorValor);
            lblTotalEscrito.setText(valornaTela);
            JOptionPane.showMessageDialog(this, "Produto retirado com sucesso.");
            ((DefaultTableModel) tabelaVenda.getModel()).removeRow(linha);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Produto.", "Pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoProdActionPerformed

    private void FinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarVendaActionPerformed
        ButtonModel selectedButton = buttonGroup1.getSelection();

        if (selectedButton == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma forma de pagamento.");
        } else {
            char formaPagamentoChar = (char) selectedButton.getMnemonic();
            String formapg = "";

            switch (formaPagamentoChar) {
                case 'D':
                    formapg = "Dinheiro";
                    break;
                case 'P':
                    formapg = "Pix";
                    break;
                case 'Y':
                    formapg = "Picpay";
                    break;
                case 'T':
                    formapg = "Cartão de Débito";
                    break;
                case 'W':
                    formapg = "Cartão de Crédito";
                    break;
                default:
                    break;
            }

            if (clienteSelecionado != null) {
                String data = dataVenda.getText();
                int idVenda = gerIG.getInstance().getGerDom().inserirVenda(clienteSelecionado, formapg, tabelaVenda, dataVenda.getText());
                JOptionPane.showMessageDialog(this, "Venda " + idVenda + " Concluída com sucesso sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cliente.");
            }
        }

    }//GEN-LAST:event_FinalizarVendaActionPerformed

    private void CancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarVendaActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarVendaActionPerformed

    private void HistVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistVendasMouseClicked
        GerInterGrafica.getInstance().abrirJanelaHistVendas();
    }//GEN-LAST:event_HistVendasMouseClicked

    private void btnHistVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistVendaActionPerformed
        vendaSelecionada = GerInterGrafica.getInstance().abrirJanelaHistVendas();
        if (vendaSelecionada != null) {
            try {
                preencherCampos(vendaSelecionada);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            limparCampos();
        }

    }//GEN-LAST:event_btnHistVendaActionPerformed

    private void txtFildCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFildCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFildCodClienteActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        ButtonModel selectedButton = buttonGroup1.getSelection();

        if (selectedButton == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma forma de pagamento.");
        } else {
            char formaPagamentoChar = (char) selectedButton.getMnemonic();
            String formapg = "";

            switch (formaPagamentoChar) {
                case 'D':
                    formapg = "Dinheiro";
                    break;
                case 'P':
                    formapg = "Pix";
                    break;
                case 'Y':
                    formapg = "Picpay";
                    break;
                case 'T':
                    formapg = "Cartão de Débito";
                    break;
                case 'W':
                    formapg = "Cartão de Crédito";
                    break;
                default:
                    break;
            }
            String data = dataVenda.getText();
            int idVenda = gerIG.getInstance().getGerDom().alterarVenda(vendaSelecionada, formapg, tabelaVenda, dataVenda.getText());
            JOptionPane.showMessageDialog(this, "Venda " + idVenda + " alterada com sucesso sucesso.");
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void preencherCamposCliente(Cliente cliente) throws ParseException {
        if (cliente != null) {
            int codigoCliente = cliente.getIdCliente();
            String codigoString = String.valueOf(codigoCliente);

            txtFildCodCliente.setText(String.valueOf(cliente.getIdCliente()));
            txtNomeCliente.setText(cliente.getNome());
            txtCpf.setText(cliente.getCpf());
            txtCelular.setText(cliente.getCelular());

        }

    }

    private void preencherCamposProduto(Produto produto) throws ParseException {
        if (produto != null) {
            int codigoProduto = produto.getIdProduto();
            String codigoString = String.valueOf(codigoProduto);
            int valor = (int) produto.getValor();
            String valorString = String.valueOf(valor);

            txtCodProduto.setText(codigoString);
            txtProduto.setText(produto.getNome());
            txtValorUn.setText(valorString);

        }

    }

    private void adicionarTabela(Produto produto, int qtde, double valortotal) {

        ((DefaultTableModel) tabelaVenda.getModel()).addRow(new Object[4]);

        int linha = tabelaVenda.getRowCount() - 1;
        int col = 0;
        tabelaVenda.setValueAt(produto, linha, col++);
        tabelaVenda.setValueAt(qtde, linha, col++);
        tabelaVenda.setValueAt(produto.getValor(), linha, col++);
        tabelaVenda.setValueAt(valortotal, linha, col++);
    }

    private void preencherCampos(Venda venda) throws ParseException {
        if (venda != null) {
//            Cliente
            txtFildCodCliente.setText(venda.getCliente().getNome());
            dataVenda.setText(venda.getDataVenda());
            txtNomeCliente.setText(venda.getCliente().getDtNascFormatada());
            txtCpf.setText(venda.getCliente().getCpf());
            txtCelular.setText(venda.getCliente().getLogradouro());

            txtFildCodCliente.setEnabled(false);
            dataVenda.setEnabled(false);
            txtNomeCliente.setEnabled(false);
            txtCpf.setEnabled(false);
            txtCelular.setEnabled(false);
            buttonPesqCliente.setVisible(false);
//            formapgto
            char formapg = ' ';
            switch (venda.getFormaPagamento()) {
                case "Dinheiro":
                    formapg = 'D';
                    break;
                case "Pix":
                    formapg = 'P';
                    break;
                case "Picpay":
                    formapg = 'Y';
                    break;
                case "Cartão de Débito":
                    formapg = 'T';
                    break;
                case "Cartão de Crédito":
                    formapg = 'W';
                    break;
                default:
                    break;
            }
            selecionarFormaPagamento(formapg);

//            produto
            DefaultTableModel model = (DefaultTableModel) tabelaVenda.getModel();
            model.setRowCount(0);

            for (ItemVenda item : venda.getItensVenda()) {
                Produto produto = item.getProduto();
                int qtde = item.getQtdProduto();
                double valortotal = item.getValorTotalPorQtdProduto();

                adicionarTabela(produto, qtde, valortotal);
            }
        }
        habilitarBotoes();
    }

    private void selecionarFormaPagamento(char formaPagamentoChar) {
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            char buttonMnemonic = (char) Character.toUpperCase(button.getMnemonic());

            if (formaPagamentoChar == buttonMnemonic) {
                button.setSelected(true);
                break;
            }
        }
    }

    private void habilitarBotoes() {
        if (vendaSelecionada == null) {
            FinalizarVenda.setVisible(true);
            btnAlterar.setVisible(false);
        } else {
            FinalizarVenda.setVisible(false);
            btnAlterar.setVisible(true);
        }
    }

    private void limparCampos() {
        clienteSelecionado = null;
        produtoSelecionado = null;
        itendsDaListaProduto = null;
        vendaSelecionada = null;

        txtFildCodCliente.setText("");
        dataVenda.setText("");
        txtNomeCliente.setText("");
        txtCpf.setText("");
        txtCelular.setText("");

        txtCodProduto.setText("");
        txtProduto.setText("");
        SpinnerQtdProduto.setValue(0);
        txtValorUn.setText("");
        txtValorTotal.setText("");
        habilitarBotoes();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarVenda;
    private javax.swing.JButton FinalizarVenda;
    private javax.swing.JMenu HistVendas;
    private javax.swing.JSpinner SpinnerQtdProduto;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnHistVenda;
    private javax.swing.JButton buttonAddProd;
    private javax.swing.JButton buttonCadCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPesqCliente;
    private javax.swing.JButton buttonPesqProduto;
    private javax.swing.JButton buttonRemoProd;
    private javax.swing.JFormattedTextField dataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lblCredito;
    private javax.swing.JRadioButton lblDebito;
    private javax.swing.JRadioButton lblDinheiro;
    private javax.swing.JRadioButton lblPicpay;
    private javax.swing.JRadioButton lblPix;
    private javax.swing.JLabel lblTotalEscrito;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtFildCodCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorUn;
    // End of variables declaration//GEN-END:variables
}
